// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace dsc_vsix
{
    internal sealed partial class Vsix
    {
        public const string _id = "dsc_vsix.c53fea6f-92c9-405f-b378-905869b5f2b3";
        public const string _name = "dsc vsix";
        public const string _description = @"Empty VSIX Project.";
        public const string _language = "en-US";
        public const string _version = "1.0";
        public const string _author = "Mads Kristensen";
        public const string _tags = "";
    }
}
