// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace dsc_vsix
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string _main_guid_string = "5b627171-e919-4075-837c-2b5eadaf7f6e";
        public static Guid _main_guid = new Guid(_main_guid_string);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int _dsc_menu_group = 0x0001;
        public const int _commands_order_includes = 0x0100;
    }
}